import { CalendarDays, DollarSign, FolderKanban, RefreshCw, Trash2, Users } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import API_URL from "../../Config/api";

const getItems = (data) => data.projects || data.data?.projects || data.items || data.data || [];
const statusColors = { active: "text-emerald-200 bg-emerald-400/10", completed: "text-cyan-200 bg-cyan-400/10", pending: "text-amber-200 bg-amber-400/10", cancelled: "text-red-200 bg-red-400/10" };

export default function AdminProjects() {
  const [projects, setProjects] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { try { setLoading(true); const response = await fetch(`${API_URL}/api/admin/projects`, { headers: { Authorization: `Bearer ${localStorage.getItem("userToken")}` }, credentials: "include" }); const data = await response.json(); if (!response.ok) throw new Error(data.message || "Unable to load projects."); setProjects(getItems(data)); } catch (requestError) { setError(requestError.message); } finally { setLoading(false); } }, []);
  useEffect(() => {
    // Fetch the initial resource after subscribing to the refresh lifecycle.
    // eslint-disable-next-line react-hooks/set-state-in-effect
    load();
    const timer = window.setInterval(load, 30000);
    return () => window.clearInterval(timer);
  }, [load]);
  const remove = async (id) => { if (!window.confirm("Delete this project?")) return; await fetch(`${API_URL}/api/admin/projects/${id}`, { method: "DELETE", headers: { Authorization: `Bearer ${localStorage.getItem("userToken")}` }, credentials: "include" }); load(); };
  return <div><div className="flex items-end justify-between"><div><p className="text-sm font-semibold uppercase tracking-[.2em] text-violet-400">Admin management</p><h1 className="mt-2 text-3xl font-bold">Projects</h1><p className="mt-2 text-slate-400">Track delivery, budgets, deadlines, and assigned teams.</p></div><button onClick={load} disabled={loading} className="rounded-xl border border-white/10 bg-white/5 p-3 hover:bg-white/10 disabled:opacity-50"><RefreshCw size={18} className={loading ? "animate-spin" : ""} /></button></div>{error && <p className="mt-6 rounded-xl border border-red-400/20 bg-red-400/10 p-4 text-red-200">{error}</p>}{loading && !projects.length ? <p className="mt-10 text-center text-slate-400">Loading projects...</p> : <div className="mt-8 grid gap-6 md:grid-cols-2 xl:grid-cols-3">{projects.map((project) => <article key={project._id || project.id} className="rounded-3xl border border-white/10 bg-[#151B30]/90 p-6 shadow-xl"><div className="flex items-start justify-between"><span className="rounded-xl bg-violet-500/15 p-3 text-violet-300"><FolderKanban size={22} /></span><span className={`rounded-full px-3 py-1.5 text-xs font-semibold ${statusColors[project.status] || "bg-white/10 text-slate-300"}`}>{project.status || "pending"}</span></div><h2 className="mt-5 text-xl font-semibold">{project.name || "Untitled project"}</h2><p className="mt-2 line-clamp-2 text-sm leading-6 text-slate-400">{project.description || "No description provided."}</p><div className="mt-6 space-y-3 text-sm text-slate-400"><p className="flex items-center gap-2"><Users size={16} className="text-violet-300" />{Array.isArray(project.team) ? `${project.team.length} team members` : project.team || "No team assigned"}</p><p className="flex items-center gap-2"><CalendarDays size={16} className="text-violet-300" />Deadline: {project.deadline ? new Date(project.deadline).toLocaleDateString() : "—"}</p><p className="flex items-center gap-2"><DollarSign size={16} className="text-violet-300" />Budget: {project.budget ?? "—"}</p></div><div className="mt-6"><div className="flex justify-between text-xs text-slate-400"><span>Progress</span><span>{project.progress ?? 0}%</span></div><div className="mt-2 h-2 rounded-full bg-white/10"><div className="h-2 rounded-full bg-gradient-to-r from-indigo-500 to-fuchsia-500" style={{ width: `${Math.min(Math.max(Number(project.progress) || 0, 0), 100)}%` }} /></div></div><button onClick={() => remove(project._id || project.id)} className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-red-300 hover:text-red-200"><Trash2 size={16} />Delete project</button></article>)}</div>}{!loading && !projects.length && <div className="mt-10 rounded-3xl border border-dashed border-white/10 p-12 text-center text-slate-500">No projects found.</div>}</div>;
}
